import './globals.css'
import { Manrope } from 'next/font/google'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";

config.autoAddCss = false;
const manrope = Manrope({
  weight:"300",
  subsets:["cyrillic"]
})

export const metadata = {
  title: 'Ejam Test',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>{children}</body>
    </html>
  )
}
